default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: awesome_blog_development

test:
  <<: *default
  database: awesome_blog_test

production:
  <<: *default
  database: awesome_blog_production
  username: awesome_blog
  password: <%= ENV['awesome_blog_DATABASE_PASSWORD'] %>

Default: &default
  Adapter: postgresql
  Encoding: unicode
  Pool: 5
